# Site setings
name: 'Oisin'
description: 'SCUBA Diver | CTO | Advisor'
meta_description: 'Oisin Mulvihill.'
logo:
# Author image is used in site sidebar and greetings in the home page hero text
author:
  image: 'authorimage.jpg'
  greetings: "Welcome to my internet island 🏝"
favicon: 'assets/images/favicon.ico'
baseurl: 
production_url: https://highfalcon.com/
disqus: 
mailchimp_url: 
# Add your GA Tracking Id
ga_analytics:

# Contact form setings
email: oisin.mulvihill@gmali.com
contact_page_description: 
thankyou_page_description: 

# Social links
twitter: 'oisinmulvihill'
facebook:
github: 'oisinmulvihill'
codepen:
dribbble:
medium: '@oisin.mulvihill'
instagram: 'oisinmulvihill'
pinterest:
linkedin: 'oisinmulvihill'
producthunt:
quora:
stackoverflow: '932855/oisin'

# Navigation
navigation:
  - text: Home
    url: /
  - text: About
    url: /about
  - text: CV
    url: /CV
#  - text: Search
#    url: /search

# Required Plugins
plugins_dir:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap

# Pagination
paginate: 5
paginate_path: /page:num/

# Permalinks
permalink: /:title

# Other
markdown: kramdown

# Sass
sass:
  sass_dir: _sass
  style: compressed
